version: '2.1'

jobs:
  test:
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: 'Build'
          command: 'CARGO_NET_GIT_FETCH_WITH_CLI=true cargo build --release -v --locked'
      - run:
          name: 'Lint'
          command: 'cargo clippy'
      - run:
          name: 'Test'
          command: 'cargo test'
    docker:
      - image: cimg/rust:1.56.0

workflows:
  lint-test-build:
    jobs:
      - test:
          filters:
            branches:
              only:
                - main

